### ISSUE TITLE
problem with subs of some links

### ISSUE THREAD

**Issue by kingoflions** [LyndaSub/LyndaSub#12]
its just doesnt work with all links for examlpe i need this link: http://www.lynda.com/iP-tutorials/What-subnet-mask/184143/187396-4.html 
can you help us thanks you are doing a great job

**Comment by theshem** [comment]
URLs should point to the initial chapter of each course. See #3.

**Comment by kingoflions** [comment]
yes i tray with the initial chapter  the welcom vid or into but the same problem

**Comment by theshem** [comment]
@kingoflions Yes. That's because of another issue we are having. See: #6

**Comment by kingoflions** [comment]
please inform us when its work again, thx Mr hashem u r the best
