### ISSUE TITLE
Weekly series problem

### ISSUE THREAD

**Issue by phanmanh159** [LyndaSub/LyndaSub#2]
It seems that it's not work with weekly series courses... Please help...

**Comment by theshem** [comment]
@phanmanh159 Weekly series usually take more time than regular courses as they may have hundreds of chapters.

As of now, LyndaSub tries to fetch all transcriptions per request, therefore it'll push the server and may take about 10-15 mins or more for weekly series.

However we're open to change the logic in a way that it fits our audiences' needs. So, if you have any ideas, we'll be all ears!

Cheers.

**Comment by phanmanh159** [comment]
http://www.lynda.com/Illustrator-tutorials/Dekes-Techniques/76067-2.html

I've tried with this link for a hour but nothing comes out. Is there any problem? Thank you.

**Comment by theshem** [comment]
@phanmanh159 Seems it exceeds the allocated memory of server. We've increased the memory, so please give it another try.

However, the better solution is to rewrite the whole application in a more efficient way in terms of performance or to improve the config of our web server which both of them take time.

**Comment by phanmanh159** [comment]
Thank you for your action HashemQolami. But it still does not work.

Could you please try with this link?

**Comment by alibo** [comment]
@phanmanh159 Fixed by #28
