### ISSUE TITLE
Please anyone tell me, is there an alternative to get lynda sub instead of this?

### ISSUE THREAD

**Issue by dendihandian** [LyndaSub/LyndaSub#22]

**Comment by aliab** [comment]
Yes, there is an alternative and that is lynda.com.

**Comment by sane4ek** [comment]
lol

**Comment by dendihandian** [comment]
its transcript, not .srt :(

**Comment by StanislavMayorov** [comment]
I stated to use 10-Day free trial at lynda.com.

**Comment by jacko1994** [comment]
http://www.softpedia.com/get/Multimedia/Video/Other-VIDEO-Tools/Lynsub.shtml
It worked well

**Comment by StanislavMayorov** [comment]
> http://www.softpedia.com/get/Multimedia/Video/Other-VIDEO-Tools/Lynsub.shtml
> It worked well

No. It downloads str only for free videos. You can check it.

**Comment by StanislavMayorov** [comment]
There are about 250 courses with subtitle on the link http://www.jiaochengonline.com/lynda-web-training-tutorials/

**Comment by theshem** [comment]
@dendihandian LyndaSub is back again. However in case of alternatives, I'm afraid I cannot help. If there's any please let me know so that I can get some rest for a while :-)

**Comment by theshem** [comment]
Oops, sorry I closed the topic mistakenly.

**Comment by jacko1994** [comment]
Haha thank you anyway. You are savior
