### ISSUE TITLE
Fix it Manually!

### ISSUE THREAD

**Issue by shahram221** [LyndaSub/LyndaSub#24]
You can see every subtitle of films in lynda.com with url like this:
http://www.lynda.com/ajax/player/transcript?courseId=105327&videoId=114091
First number (105327) is id of the course and second number (114091) is id of a video in that course.
Also you can analysis links of the course with bellow url or something like that:
http://rapid.searchmetrics.com/en/seo-tools/link-tools/outbound-links,50.html
Shahram

**Comment by ghost** [comment]
Can you generate subtitle of films in lynda.com automatically? It's so hard and long to creat a .srt.
Please do it. Thanks you so much

**Comment by StanislavMayorov** [comment]
Thank you. It works!
Maybe I will write a python script.

**Comment by theshem** [comment]
@shahram221 Nice catch! However the issue has been fixed now. Please let me know if there's still any problems.

BTW, we didn't use that internal API as the accessibility may change in the future.

**Comment by shahram221** [comment]
lyndasub is works fine.
Thank you so much

**Comment by theshem** [comment]
@shahram221 :+1: Cheers!
