### ISSUE TITLE
Unabled to find Chapers

### ISSUE THREAD

**Issue by Xml2000** [LyndaSub/LyndaSub#28]
These two links do not work
http://www.lynda.com/Marketing-Enterprise-Marketing-tutorials/SEO-Fundamentals/187858-2.html
http://www.lynda.com/Google-Maps-tutorials/SEO-Local-Visibility/178132-2.html

**Comment by theshem** [comment]
@Xml2000 Thanks for letting us know. We'll get on it.

**Comment by theshem** [comment]
@Xml2000 We just released the new major version v3.0.0 of LyndaSub.ir. Re-coded the application entirely and improved the performance—in some cases about 50+ times.
