### ISSUE TITLE
Unable to fetch transcript 

### ISSUE THREAD

**Issue by farhadibehnam** [LyndaSub/LyndaSub#3]
hi

When I download I were faced with this error:

course : http://www.lynda.com/C-tutorials/Creating-C-delegates/370499/408655-4.html

Error :Unable to fetch transcript from: http://www.lynda.com/C-tutorials/Creating-C-delegates/370499/408655-4.html

**Comment by theshem** [comment]
@farhadibehnam 

That's because the URL doesn't match the _main URL_ of the course. I.e. URLs point to chapters other than `introduction/welcome` are NOT valid.

Therefore, in this particular case, it should have been:
`http://www.lynda.com/C-tutorials/C-Delegates-Events-Lambdas/370499-2.html`
