### ISSUE TITLE
List of no working links

### ISSUE THREAD

**Issue by sane4ek** [LyndaSub/LyndaSub#30]
http://www.lynda.com/Audio-Music-Business-Skills-tutorials/Selling-Music-MP3s-Streams-CDs/163755-2.html
http://www.lynda.com/Genesis-tutorials/Customizing-Themes-Genesis-WordPress/170288-2.html
http://www.lynda.com/HTML-tutorials/Creating-HTML5-Banner-Ad-GreenSock-GSAP/373558-2.html
http://www.lynda.com/Illustrator-tutorials/Illustrator-CC-Web-Design-Aesthetics/368389-2.html
http://www.lynda.com/Web-Design-tutorials/Running-Web-Design-Business-Defining-Success/161812-2.html
http://www.lynda.com/YouTube-tutorials/Marketing-Monetizing-YouTube/181240-2.html
http://www.lynda.com/Ableton-Live-tutorials/Songwriting-Ableton-Live/178117-2.html
http://www.lynda.com/Marketing-Lead-Generation-tutorials/Google-AdWords-Essential-Training/368574-2.html
http://www.lynda.com/DAWs-tutorials/Getting-Started-Audio-Music-Production/141504-2.html
http://www.lynda.com/Audio-Music-Business-Skills-tutorials/Selling-Music-Merchandise/163756-2.html
http://www.lynda.com/YouTube-tutorials/YouTube-Musicians-Bands/135379-2.html
http://www.lynda.com/WordPress-tutorials/Start-Theme-Creative-Portfolios-WordPress/108127-2.html
http://www.lynda.com/HTML-tutorials/Up-Running-HTML5-Video/135356-2.html
http://www.lynda.com/WordPress-3-0-tutorials/WordPress-3-Building-Child-Themes/77859-2.html
http://www.lynda.com/CSS-tutorials/HTML5-Projects-Personalized-Ads/118955-2.html
http://www.lynda.com/CSS-tutorials/HTML5-Projects-Interactive-Charts/122424-2.html
http://www.lynda.com/WordPress-tutorials/WordPress-DIY-Small-Business-Website/369758-2.html
http://www.lynda.com/Genesis-tutorials/Up-Running-Genesis-WordPress/170289-2.html
http://www.lynda.com/WordPress-tutorials/WordPress-Developer-Tips-Using-Custom-Web-Fonts/169880-2.html
http://www.lynda.com/WordPress-tutorials/WordPress-Plugins-Advanced-Custom-Fields/169877-2.html
http://www.lynda.com/WordPress-tutorials/WordPress-Plugins-Social-Media-Buttons/169878-2.html
http://www.lynda.com/WordPress-tutorials/WordPress-Ecommerce-Easy-Digital-Downloads/122465-2.html
http://www.lynda.com/Web-Design-tutorials/Running-Web-Design-Business-Defining-Your-Business-Structure/163952-2.html
http://www.lynda.com/Educational-Technology-tutorials/WordPress-Classroom/423998-2.html
http://www.lynda.com/PowerShell-tutorials/Up-Running-PowerShell-Integrated-Scripting-Environment/376983-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Grunge-Poster/155653-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Victorian-Ad/155652-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Punk-Album-Art/173879-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Constructivist-Poster/155655-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Art-Nouveau-Poster/155656-2.html
http://www.lynda.com/Illustrator-tutorials/Type-Project-Dada-Poster/155654-2.html
http://www.lynda.com/Illustrator-CS4-tutorials/designing-a-cd-cover-hands-on-workshop/53855-2.html

**Comment by theshem** [comment]
@sane4ek Fixed by #28.
