### ISSUE TITLE
Problem "Unable to download chapters..."

### ISSUE THREAD

**Issue by CaraBon** [LyndaSub/LyndaSub#31]
Hello!
Thanks to the developers of the wonderful service.

Unfortunately, it is impossible to download subtitles from several courses:
http://www.lynda.com/Rhino-tutorials/Building-Game-Controller-Rhino/417076-2.html
http://www.lynda.com/Rhino-tutorials/Rhino-Projects-Building-Gaming-Console/384739-2.html
http://www.lynda.com/RhinoCAM-tutorials/Up-Running-RhinoCAM/160106-2.html
http://www.lynda.com/Bongo-tutorials/Animation-Rhino-Bongo/188676-2.html

I hope that will be able to fix.

**Comment by theshem** [comment]
@CaraBon Hi. Thanks for letting us know. Fixed by #28.
