### ISSUE TITLE
Some subtitles are not working..

### ISSUE THREAD

**Issue by mahbubrajj** [LyndaSub/LyndaSub#34]
I am a regular user of lyndasub.ir. I've downloaded many subtitles of lynda.com. But recently noticed that some links are not working. As example: "http://www.lynda.com/Premiere-Pro-tutorials/Commercial-Editing-Techniques-Premiere-Pro/122430-2.html" link is not working.
![work 2 days](https://cloud.githubusercontent.com/assets/6182662/12972064/30d4dbcc-d0cc-11e5-9da1-8c7111468694.PNG)

**Comment by theshem** [comment]
@mahabubrajj Hi, thanks for the feedback, The issue is solved by #28
