### ISSUE TITLE
About the rows

### ISSUE THREAD

**Issue by noahxiong** [LyndaSub/LyndaSub#39]
Hi, I love your site. I think it's great. It would be better if you change the subtitle from one row to two in each timeline. Thx:)

**Comment by StanislavMayorov** [comment]
I disagree.

**Comment by vito13** [comment]
i  like  you site，   i can   watch   video     and   read you    sub，  my  english  not  well，  but  i can use
google translate，  i am  chinese，  i can use you sub study    it，   and  english~~~

**Comment by chosen1stold** [comment]
@vito13  可以的 不过可以试试更快的方法 自动翻译字幕
比如SRT Translator这种

**Comment by pendave** [comment]
Substile Edit 里面就有Google的自动翻译哦
