### ISSUE TITLE
Bookmarklet request

### ISSUE THREAD

**Issue by Shakil-Shahadat** [LyndaSub/LyndaSub#4]
A bookmarklet will be great for quickly downloading subtitles. I hope you know what bookmarklet is. If you do the back end coding, I can provide you the bookmarklet code. Here is a very simple one.

``` javascript
javascript:(function(){ window.open('http://www.lyndasub.ir/?url='+encodeURIComponent(location.href)); })();
```

**Comment by Shakil-Shahadat** [comment]
Hi, this is all you need to enable bookmarklet feature. Just replace this with the current input tag.

``` php
<input type="text" class="clearfix" value="<?php if ( isset( $_GET[ "lyndaURL" ] ) ) echo $_GET[ "lyndaURL" ] ?>">
```

**Comment by theshem** [comment]
@Shakil-Shahadat Thanks, we'll take this feature into consideration for the next update.

As an aside, the [second comment](https://github.com/LyndaSub/LyndaSub/issues/4#issuecomment-169260613) opens doors to XSS attacks. All user inputs should be sanitized and filtered before getting inserted in the page.

**Comment by Shakil-Shahadat** [comment]
Yup definitely, I just wanted to give you a head start on this. Hope this won't take long.

**Comment by mostafa275** [comment]
Thanks for all the efforts you are making!

**Comment by waqas44** [comment]
http://www.lyndasub.ir/ is not working anymore. Can you fix it.

**Comment by theshem** [comment]
@waqas44 Could you please elaborate, in a [new issue](https://github.com/LyndaSub/LyndaSub/issues/new)?

**Comment by waqas44** [comment]
@HashemQolami  Thanks for reply. It was my Chrome Browser issue. It's Working so far now :)

**Comment by pendave** [comment]
I use ClipConverter which has this kind of bookmarklet.

http://www.clipconverter.cc/addon/
![6vjm3f hc_ xw1b0w3 g i](https://cloud.githubusercontent.com/assets/1331881/18823169/0c355f72-83ea-11e6-9f9e-988a2324db92.png)

If lyndasub.ir provides a bookmarlet like this, when you open  the course URL then click on the button, it will save time :)

**Comment by pendave** [comment]
Here's my way adding a bookmarklet for Chrome

`javascript:(function(){ window.open('http://www.lyndasub.ir/download?json=1&url='+encodeURIComponent(location.href)); })();`

It's nice working if you deal with IDM (Internet Download Manager), also you need JSON formatter plugin for 
[Tampermonkey - Chrome Extension](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=zh-CN)
[Greasymonkey - Firefox Add-on](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)

https://greasyfork.org/en/scripts/10718-json-formatter

If you are good at scripting, you can make your own js script just like
https://greasyfork.org

Google the lynda tutorial
![2016-10-21_141447](https://cloud.githubusercontent.com/assets/1331881/19588509/cd07cbb0-9798-11e6-8081-5b0ec0b84445.png)

Open the tutorial link on Lynda.com, then click the Bookmarklet
![2016-10-21_141559](https://cloud.githubusercontent.com/assets/1331881/19588545/062e7a92-9799-11e6-8189-2f081ba03593.png)

And you see the downlaod link in the new opened tab already in formatted json. Then click the URL it will be highlighted, right click mouse and downoad it with IDM.
![2016-10-21_141712](https://cloud.githubusercontent.com/assets/1331881/19588578/4d7379ac-9799-11e6-9884-25cf49f91dd8.png)

**Comment by pendave** [comment]
Already created a js plugin for Greasymonkey :)

https://greasyfork.org/

**Comment by Shakil-Shahadat** [comment]
@pendave can you please provide the link for the plugin?
