### ISSUE TITLE
subtitle

### ISSUE THREAD

**Issue by aliali3000** [LyndaSub/LyndaSub#46]
hello can i use subtitle of your site for my site?
سلام می تونم بعضی از زیرنویس هایی که از سایتتون دانلود میکنم رو با تغییر در سایتم استفاده کنم؟

**Comment by theshem** [comment]
We do not have any policy regarding any further use of the subtitles.
LyndaSub is a non-profit tool, that is, how you would use it is all your choice.

The only support we expect is that you cite us.
