### ISSUE TITLE
develop it for team tree house

### ISSUE THREAD

**Issue by iHMahmoodi** [LyndaSub/LyndaSub#47]
hi
thanks for your helpful service especially for Iranian 

why you not develop it for [teamtreehouse.com](https://teamtreehouse.com)

Thanks

**Comment by theshem** [comment]
Hi @iHMahmoodi,

Thank you for your kind feedback. Regarding the support of the other online training websites, have a look at my comment [here](https://github.com/LyndaSub/LyndaSub/issues/48#issuecomment-241361056).
