### ISSUE TITLE
[Bug] Error "Unable to find chapters" while courses already have subtitles

### ISSUE THREAD

**Issue by omareg94** [LyndaSub/LyndaSub#49]
It gives "Unable to find chapters" error while trying to capture courses:
https://www.lynda.com/Illustrator-tutorials/Illustrator-Fashion-Design-Creating-Brushes/124093-2.html
https://www.lynda.com/Illustrator-tutorials/Illustrator-Fashion-Design-Drawing-Flats/115431-2.html
https://www.lynda.com/Photoshop-tutorials/Photoshop-Fashion-Design-Rendering-Techniques/143325-2.html

All these courses already have subtitles.
Could you please fix this bug.

**Comment by alibo** [comment]
@omareg94 fixed :)
