### ISSUE TITLE
Subtitle generator fails 

### ISSUE THREAD

**Issue by talcod** [LyndaSub/LyndaSub#51]
Subtitle generator fails  for  **Building PDFs with Acrobat XI**   .
Link ;   https://www.lynda.com/Acrobat-tutorials/Building-PDFs-Acrobat-XI/123550-2.html  

I get ; Unable to find chapters

Could your improve it , please!
Sincerely yours ,
@talcod

**Comment by alibo** [comment]
@talcod fixed :)

**Comment by talcod** [comment]
Big thanks for the prompt reply!
Nice job , all works now .
