### ISSUE TITLE
ZipArchive::close(): Failure to create temporary file: Disk quota exceeded

### ISSUE THREAD

**Issue by mostafa275** [LyndaSub/LyndaSub#56]
Hi and thanks for the time and energy that you are putting here.
I am getting this error: 
ZipArchive::close(): Failure to create temporary file: Disk quota exceeded
I would appreciate if you could help.

**Comment by Seenveen** [comment]
Me too also getting same error. actually we are all facing this error duo to Disk quota exceeded. disk needs to clear right now disk is maybe full. admin please do something. waiting for reply.
