### ISSUE TITLE
Unable to find chapters again, help !

### ISSUE THREAD

**Issue by jacko1994** [LyndaSub/LyndaSub#6]
http://www.lynda.com/Java-tutorials/Foundations-Programming-Object-Oriented-Design/96949-2.html
This course has already sub but something wrong pls help !

**Comment by theshem** [comment]
@jacko1994 Hi,
Thanks for letting us know. LyndaSub has been stopped due to some problems with accessing the transcripts. However we are working on it to get it back to work.
Stay tuned! We'll get back soon.

**Comment by theshem** [comment]
Oops I closed this issue mistakenly :)

**Comment by nmpountou** [comment]
SAME PROBLEM!!!!!
http://www.lynda.com/Bootstrap-tutorials/Bootstrap-3-Essential-Training/417641-2.html

**Comment by nmpountou** [comment]
SAME HERE!
http://www.lynda.com/HTML-5-tutorials/HTML5-Background-Processes-with-Web-Workers/85868-2.html

**Comment by jacko1994** [comment]
Ok I see! Cheer ups Admin! We always need you :)

**Comment by theshem** [comment]
@nmpountou That's right. None of the links are working now, but we are on it to get it to work again.

**Comment by kingoflions** [comment]
please inform us when its work again, thx Mr hashem u r the best

**Comment by Xml2000** [comment]
SAME PROBLEM! 
http://www.lynda.com/ArcGIS-tutorials/ArcGIS-Essential-Training/180108-2.html

**Comment by theshem** [comment]
@jacko1994  @nmpountou  @kingoflions  @Xml2000 LyndaSub is back again. If there is still any issues please let me know.

**Comment by login17** [comment]
Hello! It doesn't work (http://www.lyndasub.ir/), does it? Is there any alternative solution? Thanks!

**Comment by theshem** [comment]
@login17 I'm afraid not. LyndaSub is also permanently closed due to the cost of maintenance. This repo will also get deleted.
