### ISSUE TITLE
Some subtitles are not working,just first unit complete.

### ISSUE THREAD

**Issue by qyouqme** [LyndaSub/LyndaSub#64]
Some subtitles are not working,just first unit complete,other units just the first one complete,the rest just nothing.
https://www.lynda.com/Camtasia-tutorials/Camtasia-2016-Mac-Essential-Training/530081-2.html
https://www.lynda.com/Camtasia-tutorials/Camtasia-9-Windows-Essential-Training/417150-2.html

**Comment by pendave** [comment]
I also find some parts of the download subtitles are not finished yet, though the contents of transcript are already there online.
Such as "JavaScript: Enhancing the DOM"
https://www.lynda.com/HTML-tutorials/JavaScript-Enhancing-DOM/122462-2.html

![qq 20161104130304](https://cloud.githubusercontent.com/assets/1331881/19995106/15948e76-a28f-11e6-8ba5-b0a2f9584992.png)

**Comment by pendave** [comment]
I think the the official staff is not working on the time line for the scripts yet....
