### ISSUE TITLE
Lyndasub is not working

### ISSUE THREAD

**Issue by Seenveen** [LyndaSub/LyndaSub#68]
Hello respected Admins/ mods Lyndasub is not working when i open htpps://lyndasub.ir i am getting message **LyndaSub is down, be right back**
 please restore. waiting for resolved.

**Comment by ljupchokanevche** [comment]
Oh please, please come back online please

**Comment by drizzersilverberg** [comment]
if anyone know any alternatives, please tell me.

**Comment by Goudarz** [comment]
@Seenveen , @kanevsr Lyndasub is working : http://www.lyndasub.ir/index.php

**Comment by ljupchokanevche** [comment]
Is the site gone for good now???

**Comment by pisangGoreng** [comment]
link is off right now

**Comment by Seenveen** [comment]
yup. please give us alternative for lyndasub.ir  waiting for reply's.
