### ISSUE TITLE
This training Subtitle Not working  Programming Fundamentals in the Real World

### ISSUE THREAD

**Issue by WahidurRahman7** [LyndaSub/LyndaSub#7]
http://www.lynda.com/Python-tutorials/Using-exercise-files/418249/459107-4.html

**Comment by Shakil-Shahadat** [comment]
You were using a link for a single video not the link of the course. Try this http://www.lynda.com/Python-tutorials/Programming-Fundamentals-Real-World/418249-2.html

**Comment by theshem** [comment]
What @Shakil-Shahadat said. For further info: #3
