### ISSUE TITLE
Unable to fetch transcript error

### ISSUE THREAD

**Issue by behnamnazarpak** [LyndaSub/LyndaSub#8]
Hi , i try to download This Lynda course : 
www.lynda.com/Java-tutorials/Java-EE-Essentials-Servlets-JavaServer-Faces/124399-2.html
but my result is Unable to fetch transcript error.
Please help me :)

**Comment by theshem** [comment]
Hi,
Yes we are having some issues, but we'll get it to work soon. More info at: #6
